// Cloudflare Worker entry: the OpenNext build output, wrapped with the edge cache for anonymous page renders
// (src/lib/edge-cache.ts). `.open-next/worker.js` is generated by `npm run build`.
import openNext from "./.open-next/worker.js";
import { withEdgeCache } from "./src/lib/edge-cache";

const worker = {
  fetch: withEdgeCache((request, env, ctx) => openNext.fetch(request, env, ctx)),
};

export default worker;
