// Review by a German lawyer before relying on this text.
// Deutsche Fassung: rechtlich verbindlich. Alle anderen Sprachfassungen sind Übersetzungen.
import type { LegalBuilder } from "../types";

export const de: LegalBuilder = (o, ctx) => {
  const who = [o.operatorType, o.legalName].filter(Boolean).join(": ");
  const address = `${o.streetAddress}, ${o.postalCodeCity}, ${o.country}`;
  return {
    ui: {
      translationNote: "Diese Seite ist eine Übersetzung und dient nur Ihrer Information. Rechtlich verbindlich ist ausschließlich die deutsche Fassung.",
      germanLink: "Zur deutschen Fassung",
      updated: "Stand",
    },

    impressum: {
      title: "Impressum",
      description: `Impressum von REGA Platform nach § 5 DDG: Anbieter, Anschrift, Kontakt und Verantwortlicher für den Inhalt des kostenlosen kurdischen Portals.`,
      blocks: [
        { h: "Angaben gemäß § 5 DDG", p: [who, o.responsiblePerson ? `Vertretungsberechtigt / verantwortliche Person: ${o.responsiblePerson}` : "", address].filter(Boolean) },
        { h: "Kontakt", p: [`Telefon: ${o.phone}`, `E-Mail: ${o.publicEmail}`] },
        ...(o.vatId || o.tradeRegister
          ? [{ h: "Register und Steuern", p: [o.tradeRegister ? `Handelsregister: ${o.tradeRegister}` : "", o.vatId ? `Umsatzsteuer-Identifikationsnummer gemäß § 27a UStG: ${o.vatId}` : ""].filter(Boolean) }]
          : []),
        { h: "Verantwortlich für den Inhalt (§ 18 Abs. 2 MStV)", p: [`${o.responsiblePerson || o.legalName}, ${address}`] },
        { h: "Kontaktstelle nach dem Digital Services Act (Art. 11, 12 DSA)", p: [`Behörden, die Kommission und Nutzer erreichen uns elektronisch unter ${o.publicEmail}. Wir kommunizieren auf Deutsch und Englisch.`, "Rechtswidrige Inhalte können Sie über das Formular unter „Inhalt melden“ anzeigen."] },
        { h: "Kostenloses Angebot", p: ["REGA Platform ist ein kostenloses Angebot. Für Nutzer und für Unternehmen entstehen keine Gebühren."] },
        { h: "Verbraucherstreitbeilegung", p: ["Wir sind weder bereit noch verpflichtet, an Streitbeilegungsverfahren vor einer Verbraucherschlichtungsstelle teilzunehmen."] },
        { h: "Haftung für Inhalte", p: ["Einträge von Unternehmen, Dienstleistungen und Standorten werden von den jeweiligen Inhabern oder von uns auf Grundlage ihrer Angaben erstellt. Als Diensteanbieter sind wir für eigene Inhalte nach den allgemeinen Gesetzen verantwortlich. Für fremde Inhalte sind wir erst ab Kenntnis einer konkreten Rechtsverletzung verantwortlich; bei Bekanntwerden entsprechender Rechtsverletzungen entfernen wir diese Inhalte umgehend.", "Angaben der KI-gestützten Antworten des REGA-Assistenten können fehlerhaft sein und ersetzen keine Beratung."] },
        { h: "Haftung für Links", p: ["Unser Angebot enthält Links zu externen Webseiten Dritter, auf deren Inhalte wir keinen Einfluss haben. Für diese fremden Inhalte übernehmen wir keine Gewähr. Verantwortlich ist stets der jeweilige Anbieter. Bei Bekanntwerden von Rechtsverletzungen entfernen wir solche Links umgehend."] },
        { h: "Urheberrecht", p: ["Die durch uns erstellten Inhalte und Werke unterliegen dem deutschen Urheberrecht. Beiträge Dritter sind als solche gekennzeichnet. Vervielfältigung, Bearbeitung und Verbreitung außerhalb der Grenzen des Urheberrechts bedürfen der Zustimmung des jeweiligen Rechteinhabers."] },
      ],
    },

    privacy: {
      title: "Datenschutzerklärung",
      description: "Datenschutzerklärung von REGA Platform: Verantwortlicher, Hosting, Konto, Kontaktformular, KI-Assistent, Cookies, Ihre DSGVO-Rechte und Beschwerderecht.",
      blocks: [
        { h: "1. Verantwortlicher", p: [`Verantwortlich für die Datenverarbeitung auf dieser Website im Sinne der Datenschutz-Grundverordnung (DSGVO) ist:`, `${who}, ${address}`, `E-Mail: ${o.publicEmail} · Telefon: ${o.phone}`] },
        { h: "2. Überblick", p: ["REGA Platform ist ein kostenloses Verzeichnis für die kurdische Community in Deutschland und Europa. Wir verarbeiten personenbezogene Daten nur, soweit dies für den Betrieb der Website, Ihr Benutzerkonto, die Kommunikation mit Ihnen und den Schutz des Angebots erforderlich ist. Wir verkaufen keine Daten und betreiben keine Werbe- oder Tracking-Netzwerke."] },
        { h: "3. Hosting und Server-Logfiles", p: [`Die Website wird bei ${o.hostingProvider} betrieben. Beim Aufruf verarbeitet der Hosting-Anbieter technisch notwendige Daten, insbesondere IP-Adresse, Datum und Uhrzeit, aufgerufene Seite, Browsertyp und Betriebssystem. Dies dient der Auslieferung, der Stabilität und der Abwehr von Angriffen.`, "Rechtsgrundlage ist Art. 6 Abs. 1 lit. f DSGVO (berechtigtes Interesse an einem sicheren und stabilen Betrieb). Eine Übermittlung in Drittländer kann stattfinden; sie erfolgt auf Grundlage geeigneter Garantien (EU-Standardvertragsklauseln bzw. EU-US Data Privacy Framework). Mit dem Anbieter besteht ein Auftragsverarbeitungsvertrag."] },
        { h: "4. Cookies und lokale Speicherung", p: ["Wir setzen ausschließlich technisch notwendige Speichermechanismen ein, die für den angeforderten Dienst erforderlich sind (§ 25 Abs. 2 Nr. 2 TDDDG). Deshalb zeigen wir keinen Cookie-Banner."], ul: ["Sitzungs-Cookie (Auth.js) – nur nach der Anmeldung, hält Ihre Sitzung aufrecht (bis zu 14 Tage).", "Sprach-Cookie (REGA_LOCALE / NEXT_LOCALE) – merkt sich die gewählte Sprache (1 Jahr).", "Browser-Speicher „rega-theme“ (localStorage) – merkt sich hell/dunkel.", "Sitzungsspeicher des Browsers – eine zufällige Kennung für den laufenden REGA-Assistenten-Chat; sie wird beim Schließen des Tabs gelöscht."] },
        { h: "5. Reichweitenmessung und Analyse", p: [ctx.analytics ? `Wir setzen folgendes Analyse-Werkzeug ein: ${o.analyticsTool}. Soweit dabei nicht notwendige Cookies oder ähnliche Technologien verwendet werden, holen wir vorher Ihre Einwilligung ein (§ 25 Abs. 1 TDDDG, Art. 6 Abs. 1 lit. a DSGVO).` : "Wir setzen keine Analyse- oder Tracking-Werkzeuge ein und binden keine Werbung ein."] },
        { h: "6. Benutzerkonto und Registrierung", p: ["Für Inserate und Funktionen mit Anmeldung können Sie ein Konto anlegen. Wir verarbeiten dafür Name, E-Mail-Adresse, ein gesichert gespeichertes Passwort (Hash, nie im Klartext), Kontoart (Nutzer oder Unternehmen), Sprache, den Zeitpunkt Ihrer Zustimmung zu Nutzungsbedingungen und Datenschutzerklärung, den Zeitpunkt der E-Mail-Bestätigung und der letzten Anmeldung.", `Für Bestätigungs- und Passwort-zurücksetzen-E-Mails nutzen wir einen E-Mail-Dienstleister${o.emailProvider ? ` (${o.emailProvider})` : ""} als Auftragsverarbeiter.`, "Rechtsgrundlage ist Art. 6 Abs. 1 lit. b DSGVO (Nutzungsvertrag) sowie lit. f (Sicherheit, Missbrauchsabwehr). Wir speichern die Daten, bis Sie das Konto löschen lassen."] },
        { h: "7. Kontaktformular und E-Mail", p: ["Wenn Sie das Kontaktformular nutzen, speichern wir Name, optional E-Mail-Adresse, Betreff, Nachricht und die Sprache Ihrer Seite und leiten die Nachricht per E-Mail an unser Team weiter. Die Daten dienen ausschließlich der Bearbeitung Ihrer Anfrage (Art. 6 Abs. 1 lit. b bzw. f DSGVO) und werden gelöscht, sobald sie nicht mehr erforderlich sind, spätestens nach Ablauf gesetzlicher Aufbewahrungsfristen. Zum Schutz vor Spam wird die Anzahl der Absendungen pro Verbindung begrenzt."] },
        { h: "8. Inhalte melden (Digital Services Act)", p: ["Über das Meldeformular erfassen wir die gemeldete Adresse, den Grund, Ihre Begründung sowie Ihren Namen und Ihre E-Mail-Adresse, um die Meldung zu prüfen und Ihnen das Ergebnis mitzuteilen (Art. 6 Abs. 1 lit. c DSGVO i. V. m. Art. 16 DSA). Die Daten werden so lange gespeichert, wie es für die Bearbeitung und die Dokumentation der Entscheidung erforderlich ist."] },
        { h: "9. Einträge von Unternehmen", p: ["Unternehmenseinträge (Name, Beschreibung, Anschrift, Telefon, E-Mail, Website, Öffnungszeiten, Bilder, Kartenposition) werden öffentlich angezeigt. Sie werden von den Inhabern selbst oder auf deren Veranlassung eingestellt, die dafür verantwortlich sind, dass diese Angaben veröffentlicht werden dürfen. Bilder werden in einem Objektspeicher abgelegt. Rechtsgrundlage ist Art. 6 Abs. 1 lit. b und f DSGVO.", "Bewertungen: Wenn Sie eine Bewertung schreiben, veröffentlichen wir nach Freigabe durch die Moderation den in Ihrem Konto hinterlegten Namen, Ihre Sterne, Ihren Kommentar und das Datum. Pro Unternehmen ist eine Bewertung je Nutzer möglich; Sie können sie ändern oder per E-Mail an uns löschen lassen. Rechtsgrundlage: Art. 6 Abs. 1 lit. b und f DSGVO.", "Stellen, Veranstaltungen und Ratgeber: Diese Einträge werden von Unternehmen oder von unserem Team veröffentlicht. Kontaktangaben, die ein Unternehmen für Bewerbungen angibt (E-Mail-Adresse oder Link), sind mit dem Eintrag öffentlich sichtbar. Rechtsgrundlage: Art. 6 Abs. 1 lit. b und f DSGVO."] },
        { h: "10. REGA-Assistent (KI)", p: [`Wenn Sie den REGA-Assistenten nutzen, werden Ihre Frage, der bisherige Gesprächsverlauf und passende öffentliche Einträge aus unserem Verzeichnis an unseren KI-Dienstleister übermittelt: ${o.aiProvider}. Dieser verarbeitet die Daten als Auftragsverarbeiter und kann dabei in Drittländern sitzen (Garantien: Standardvertragsklauseln).`, "Bitte geben Sie in den Chat keine sensiblen personenbezogenen Daten ein. Antworten werden von einer KI erzeugt und können fehlerhaft sein.", `Wir speichern den Chat mit einer zufälligen Sitzungskennung (ohne Name oder E-Mail, bei angemeldeten Nutzern mit Konto-Zuordnung) höchstens ${ctx.aiRetentionDays} Tage und löschen ihn dann automatisch. Rechtsgrundlage ist Art. 6 Abs. 1 lit. b und f DSGVO.`] },
        { h: "11. Standort („In der Nähe“) und Karten", p: ["Die Umgebungssuche nutzt Ihren Standort nur, wenn Sie der Abfrage Ihres Browsers zustimmen (Art. 6 Abs. 1 lit. a DSGVO). Die Koordinaten werden für die Suche an unseren Server übermittelt und nicht gespeichert. Sie können stattdessen eine Stadt wählen.", "Kartenkacheln werden direkt von einem Kartendienst geladen (Standard: OpenFreeMap, tiles.openfreemap.org, auf Basis von OpenStreetMap-Daten). Dabei wird Ihre IP-Adresse an den Kartendienst übermittelt (Art. 6 Abs. 1 lit. f DSGVO, Interesse an einer Kartendarstellung)."] },
        { h: "12. Empfänger", p: ["Empfänger sind unsere Auftragsverarbeiter (Hosting, E-Mail-Versand, KI-Dienst, Objektspeicher) sowie, wenn gesetzlich verpflichtet, Behörden. Eine Weitergabe zu Werbezwecken findet nicht statt."] },
        { h: "13. Ihre Rechte", p: ["Sie haben gegenüber uns das Recht auf Auskunft (Art. 15), Berichtigung (Art. 16), Löschung (Art. 17), Einschränkung der Verarbeitung (Art. 18), Datenübertragbarkeit (Art. 20) und Widerspruch gegen Verarbeitungen auf Grundlage berechtigter Interessen (Art. 21 DSGVO). Eine erteilte Einwilligung können Sie jederzeit mit Wirkung für die Zukunft widerrufen. Wenden Sie sich dazu an " + o.publicEmail + "."] },
        { h: "14. Beschwerderecht", p: ["Sie haben das Recht, sich bei einer Datenschutz-Aufsichtsbehörde zu beschweren, insbesondere in dem Mitgliedstaat Ihres Aufenthaltsorts oder des Orts des mutmaßlichen Verstoßes. Eine Liste der deutschen Aufsichtsbehörden finden Sie unter https://www.bfdi.bund.de/DE/Service/Anschriften/Laender/Laender-node.html."] },
        { h: "15. Bereitstellung und automatisierte Entscheidungen", p: ["Die Nutzung der öffentlichen Seiten ist ohne Angabe personenbezogener Daten möglich. Für ein Konto sind Name, E-Mail-Adresse und Passwort erforderlich. Eine ausschließlich automatisierte Entscheidungsfindung einschließlich Profiling findet nicht statt."] },
        { h: "16. Änderungen", p: ["Wir passen diese Erklärung an, wenn sich Funktionen oder Rechtslage ändern. Es gilt die jeweils hier veröffentlichte Fassung."] },
      ],
    },

    terms: {
      title: "Nutzungsbedingungen",
      description: "Nutzungsbedingungen von REGA Platform: kostenlose Nutzung ohne Gebühren, Regeln für Einträge, Moderation, Haftung und Löschung des Kontos.",
      blocks: [
        { h: "1. Geltungsbereich", p: [`Diese Bedingungen gelten für die Nutzung von REGA Platform (www.regaplatform.com), betrieben von ${who}, ${address}.`] },
        { h: "2. Kostenlos", p: ["REGA Platform ist für Nutzer und für Unternehmen vollständig kostenlos. Es gibt keine Gebühren, Abonnements, bezahlten Platzierungen oder Zahlungsfunktionen."] },
        { h: "3. Konto", p: ["Für Inserate ist ein Konto erforderlich. Sie müssen wahrheitsgemäße Angaben machen, Ihre Zugangsdaten geheim halten und uns Missbrauch Ihres Kontos unverzüglich melden. Pro Person ist ein Konto vorgesehen."] },
        { h: "4. Regeln für Einträge und Beiträge", p: ["Sie dürfen nur Inhalte einstellen, zu deren Veröffentlichung Sie berechtigt sind. Nicht erlaubt sind insbesondere:"], ul: ["rechtswidrige, beleidigende, diskriminierende oder volksverhetzende Inhalte;", "falsche oder irreführende Angaben, erfundene Unternehmen oder Bewertungen;", "Spam, Werbung für nicht zugehörige Angebote und Mehrfach-Einträge derselben Leistung;", "Inhalte, die Rechte Dritter (Urheber-, Marken-, Persönlichkeitsrechte) verletzen;", "Angaben zu Dritten ohne deren Einverständnis;", "Bewertungen, die nicht Ihrer eigenen Erfahrung entsprechen, Bewertungen des eigenen Unternehmens sowie gekaufte oder getauschte Bewertungen."] },
        { h: "5. Prüfung und „Rega Verified“", p: ["Neue Einträge werden vor der Veröffentlichung von uns geprüft und können abgelehnt oder zur Überarbeitung zurückgegeben werden. Die Kennzeichnung „Rega Verified“ bedeutet, dass wir bestimmte Angaben des Eintrags geprüft haben. Sie ist keine Empfehlung und keine Garantie für die Qualität des Angebots.", "Auch Bewertungen sowie Einträge für Stellen, Veranstaltungen und Ratgeber werden erst nach Prüfung veröffentlicht. Beiträge, die gegen diese Regeln verstoßen, dürfen wir ablehnen oder entfernen."] },
        { h: "6. Rechteeinräumung", p: ["Sie räumen uns das einfache, nicht ausschließliche Recht ein, Ihre Einträge und Bilder auf REGA Platform in allen Sprachfassungen anzuzeigen und dafür technisch zu vervielfältigen. Die Rechte verbleiben bei Ihnen."] },
        { h: "7. Meldung und Entfernung", p: ["Rechtswidrige oder regelwidrige Inhalte können über „Inhalt melden“ gemeldet werden. Wir können Inhalte entfernen und Konten sperren, wenn gegen Gesetze oder diese Bedingungen verstoßen wird; wir informieren Betroffene und nennen den Grund, soweit gesetzlich vorgesehen."] },
        { h: "8. Haftung", p: ["Wir haften unbeschränkt bei Vorsatz und grober Fahrlässigkeit, bei Verletzung von Leben, Körper und Gesundheit sowie nach dem Produkthaftungsgesetz. Bei leichter Fahrlässigkeit haften wir nur bei Verletzung wesentlicher Vertragspflichten und begrenzt auf den vorhersehbaren, typischen Schaden. Für Angaben in Einträgen, für Angebote Dritter und für die Richtigkeit KI-gestützter Antworten übernehmen wir keine Gewähr. Wir schulden keine ständige Verfügbarkeit."] },
        { h: "9. Löschung des Kontos", p: [`Sie können Ihr Konto jederzeit löschen lassen, indem Sie uns unter ${o.publicEmail} schreiben. Wir löschen Ihre Kontodaten; Einträge werden entfernt oder anonymisiert, soweit keine gesetzlichen Aufbewahrungspflichten entgegenstehen.`] },
        { h: "10. Änderungen, anwendbares Recht", p: ["Wir können diese Bedingungen mit Wirkung für die Zukunft ändern; wesentliche Änderungen kündigen wir an. Es gilt deutsches Recht; zwingende Verbraucherschutzvorschriften des Staates, in dem Sie Ihren gewöhnlichen Aufenthalt haben, bleiben unberührt. Sollten einzelne Bestimmungen unwirksam sein, bleibt der Rest wirksam."] },
      ],
    },
  };
};
